blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.awfixer.com
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://help.awfixer.com/security
    about: Please report security vulnerabilities here.
